# Server configuration (Dynamic port number)
server:
  ssl:
    enabled: false
    key-alias: ${KOJSTAR_TERMINAL_SSL_KEY_ALIAS}
    key-store: file:${KOJSTAR_TERMINAL_SSL_KEY_STORE}
    key-store-password: ${KOJSTAR_TERMINAL_SSL_KEY_PASSWORD}
    key-store-type: PKCS12
    key-password: ${KOJSTAR_TERMINAL_SSL_KEY_PASSWORD}
  port: 9001

# Spring application configuration
spring:
  application:
    name: auth-service
  datasource:
    url: ${KOJSTAR_TERMINAL_AUTH_SERVICE_DB_URL}
    username: ${KOJSTAR_TERMINAL_MYSQL_USERNAME}
    password: ${KOJSTAR_TERMINAL_MYSQL_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      max-lifetime: 60000
      validation-timeout: 3000
      idle-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  transaction:
    propagation: REQUIRED
  jackson:
    time-zone: ${KOJSTAR_TERMINAL_TIME_ZONE}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: ${KOJSTAR_TERMINAL_EMAIL_HOST}
    port: ${KOJSTAR_TERMINAL_EMAIL_PORT}
    protocol: ${KOJSTAR_TERMINAL_EMAIL_PROTOCOL}
    username: ${KOJSTAR_TERMINAL_EMAIL_USERNAME}
    password: ${KOJSTAR_TERMINAL_EMAIL_PASSWORD}
    sender: ${KOJSTAR_TERMINAL_EMAIL_SENDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    encoding: UTF-8
  redis:
    host: ${KOJSTAR_TERMINAL_SPRING_REDIS_HOST}  # Usa el nombre del servicio Docker
    port: ${KOJSTAR_TERMINAL_SPRING_REDIS_PORT}
    timeout: 5000ms
    password: ${KOJSTAR_TERMINAL_SPRING_REDIS_PASSWORD}

# JWT secret and expiration
jwt:
  secret: ${KOJSTAR_TERMINAL_JWT_SECRET}
  expiration: ${KOJSTAR_TERMINAL_JWT_EXPIRATION}

# Logging configuration
logging:
  level:
    root: INFO