# Server configuration (Dinamyc port number)
server:
  host-issuer: ${KOJSTAR_TERMINAL_AUTH_HOST_ISSUER}
  port: 8081

# Spring application configuration
spring:
  application:
    name: storage-service
  datasource:
    url: ${KOJSTAR_TERMINAL_TEST_SERVICE_DB_URL}
    username: ${KOJSTAR_TERMINAL_MYSQL_USERNAME}
    password: ${KOJSTAR_TERMINAL_MYSQL_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      max-lifetime: 60000
      validation-timeout: 3000
      idle-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  transaction:
    propagation: REQUIRED
  jackson:
    time-zone: ${KOJSTAR_TERMINAL_TIME_ZONE}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      enabled: true
      resolve-lazily: true
      file-size-threshold: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KOJSTAR_TERMINAL_OAUTH2_HOST_ISSUER}
          jwk-set-uri: ${KOJSTAR_TERMINAL_OAUTH2_HOST_ISSUER}/oauth2/jwks
  data:
    mongodb:
      host: ${KOJSTAR_TERMINAL_MONGODB_HOST}
      port: ${KOJSTAR_TERMINAL_MONGODB_PORT}
      database: ${KOJSTAR_TERMINAL_MONGODB_DATABASE}
      username: ${KOJSTAR_TERMINAL_MONGODB_USERNAME}
      password: ${KOJSTAR_TERMINAL_MONGODB_PASSWORD}
      authentication-database: ${KOJSTAR_TERMINAL_MONGODB_AUTH_DB}

# JWT secret and expiration
jwt:
  public-key-location: file:${KOJSTAR_TERMINAL_JWT_PUBLIC_KEY_LOCATION}

# Media location on the server
app:
  media:
    location: ${KOJSTAR_TERMINAL_MEDIA_LOCATION}

# Logging configuration
logging:
  level:
    root: INFO